version: "3"

services:
  ftx-back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "127.0.0.1:8081:8081" # 预留给pprof
    networks:
      - ftx
    volumes:
      - /www/ftx-site/logs:/www/ftx-site/logs
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    expose:
      - "3306"
    networks:
      - ftx
    volumes:
      - /etc/localtime:/etc/localtime
      - /www/ftx-site/mysql/cnf:/etc/mysql/conf.d
      - /www/ftx-site/mysql/data:/var/lib/mysql

networks:
  ftx:
    driver: bridge
